# .github/workflows/docker-image.yml
name: CI

on:
  push:
    branches:
      - main

# jobs:
#   build:
#     runs-on: ubuntu-latest
# 
#     steps:
#     - name: Checkout repository
#       uses: actions/checkout@v2
# 
#     - name: Set up Docker Buildx
#       uses: docker/setup-buildx-action@v1
# 
#     - name: Login to DockerHub
#       run: echo "${{ secrets.PASSWORD }}" | docker login ${{ secrets.REGISTRY }} -u ${{ secrets.USERNAME }} --password-stdin
# 
#     - name: Build and push Docker image
#       uses: docker/build-push-action@v5
#       with:
#         context: test-Docker/
#         builder: ${{ steps.buildx.outputs.name }}
#         # file: Dockerfile
#         push: true
#         #tags: ${{ secrets.USERNAME }}/test-repo:latest
#         tags: ${{ secrets.REGISTRY }}/test_repo:latest
#         #tags: '${{ secrets.REGISTRY_URL }}/my-project/server:latest'
#         cache-from: type=registry,ref=${{ secrets.REGISTRY }}/test_repo/server:buildcache'
#         cache-to: type=registry,ref=${{ secrets.REGISTRY }}/test_repo/server:buildcache,mode=max'



jobs:
      push-store-image:
        runs-on: ubuntu-latest
        # defaults:
        #   run:
        #     working-directory: './Store'
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ${{secrets.REGISTRY}}
              username: ${{secrets.USERNAME}}
              password: ${{secrets.PASSWORD}}

          - name: 'Build Inventory Image'
            run: |
              ls
              docker build . --tag ${{secrets.REGISTRY}}/test_repo:latest
              docker push ${{secrets.REGISTRY}}/test_repo:latest




              
